[auto] update nova/tools/server_side/Rakefile to newest version

diff --git a/tools/server_side/Rakefile b/tools/server_side/Rakefile
--- a/tools/server_side/Rakefile
+++ b/tools/server_side/Rakefile
@@ -124,6 +124,7 @@ end
 
 # get all build targets in a module, with a given build mode. it also sets up the final build targets
 def all_targets_in_module mod, build_mode
+  puts "Analyzing targets in #{my_join "-", [build_mode, mod]}"
   depend = {mod => []}
   action = {mod => []}
 
@@ -757,82 +758,250 @@ def gen_configure_script
 
 # Automatically generated on #{Time.now} 
 
-echo "TODO: parse parameters to configure script!"
-
+function print_help {
+  echo "This configure script is automatically generated by 'rake gen'"
+  echo "Get help: './configure -h' or './configure --help'"
+  echo ""
 #{
-  if defined? CONFIGURE_BINARIES
-    "echo \"Checking binaries\""
+if defined? CONFIGURE_HEADERS
+  <<EOF
+echo "Header files that would be checked:"
+#{
+  header_echo = CONFIGURE_HEADERS.sort.collect do |header_fn|
+    "echo \"  #{header_fn}  (use 'HAVE_#{header_fn.gsub(/\/|\./, "_").upcase}' macro)\""
   end
+  header_echo.join "\n"
+}
+echo ""
+EOF
+end
 }
 #{
-  if defined? CONFIGURE_BINARIES
-    all_binaries = CONFIGURE_BINARIES.collect do |bin_file|
-      "which #{bin_file} 2>&1 >> /dev/null\n" +
-      "if [ \"$?\" -ne \"0\" ] ; then\n" +
-      "  echo \"Binary not found: #{bin_file}\"\n" +
-      "  exit 1\n" +
-      "fi"
+if defined? CONFIGURE_LIBS
+  <<EOF
+echo "Library dependency:"
+#{
+  lib_echo = CONFIGURE_LIBS.keys.sort.collect do |lib_fn|
+    "echo \"  #{lib_fn}\""
+  end
+  lib_echo.join "\n"
+}
+echo ""
+EOF
+end
+}
+#{
+if defined? CONFIGURE_SWITCHES
+  <<EOF
+echo "Default compile switches:"
+#{
+  swt_echo = CONFIGURE_SWITCHES.keys.sort.collect do |swt|
+    if CONFIGURE_SWITCHES[swt] == "true"
+      "echo \"  --enable-#{swt}  (macro: ENABLE_#{swt.gsub("-", "_").upcase}=1)\""
+    else
+      "echo \"  --disable-#{swt}  (macro: ENABLE_#{swt.gsub("-", "_").upcase}=0)\""
     end
-    all_binaries.join "\n"
   end
+  swt_echo.join "\n"
 }
-
-test_c_file="int main(){return 0;}"
-
-#{
-  if defined? CONFIGURE_LIBS
-    "echo \"Checking libraries\""
-  end
+echo ""
+EOF
+end
 }
 #{
-  if defined? CONFIGURE_LIBS
-    all_libs = CONFIGURE_LIBS.collect do |lib_fn, err_msg|
-      "echo ${test_c_file} > configure.check.c\n" +
-      "gcc configure.check.c -l#{lib_fn[3..-1]} -o configure.check.out\n" +
-      "if [ \"$?\" -ne \"0\" ] ; then\n" +
-      "  echo \"#{err_msg}\"\n" +
-      "  rm -rf configure.check.c configure.check.out\n" + 
-      "  exit 1\n" +
-      "else\n" +
-      "  rm -rf configure.check.c configure.check.out\n" + 
-      "fi"
+if defined? CONFIGURE_OPTIONS
+  <<EOF
+echo "Default configure options:"
+#{
+  opt_echo = CONFIGURE_OPTIONS.keys.sort.collect do |opt|
+    if CONFIGURE_OPTIONS[opt] == nil
+      "echo \"  #{opt}  (empty)\""
+    else
+      "echo \"  #{opt}=#{CONFIGURE_OPTIONS[opt]}\""
     end
-    all_libs.join "\n"
   end
+  opt_echo.join "\n"
+}
+echo ""
+EOF
+end
+}
+  exit 0
+}
+
+# check if need to show help info
+for i in $*
+do
+  case $i in
+  -h)
+    print_help
+    ;;
+  --help)
+    print_help
+    ;;
+  *)
+    # unknown options
+    ;;
+  esac
+done
+
+
+# set default values
+#{
+if defined? CONFIGURE_OPTIONS
+  all_params = CONFIGURE_OPTIONS.collect do |param, value|
+    if value != nil
+      "#{param.gsub("-", "_")}=#{value}"
+    end
+  end
+  all_params.delete_if {|item| item == nil}
+  all_params.join "\n"
+end
 }
 
 #{
-  if defined? CONFIGURE_H and defined? CONFIGURE_HEADERS
-    "echo \"Generating #{CONFIGURE_H}\"\n" +
-    "rm -rf #{CONFIGURE_H}\n" +
-    "echo \"// Automatically generated by './configure' on `date`\" >> #{CONFIGURE_H}\n" +
-    "echo \"#ifndef CONFIGURE_H\" >> #{CONFIGURE_H}\n" +
-    "echo \"#define CONFIGURE_H\" >> #{CONFIGURE_H}"
+if defined? CONFIGURE_H and defined? CONFIGURE_SWITCHES
+  all_params = CONFIGURE_SWITCHES.collect do |param, value|
+    "ENABLE_#{param.gsub("-", "_").upcase}=#{value}"
   end
+  all_params.join "\n"
+end
+}
+
+# start param parsing
+for i in $*
+do
+  case $i in
+#{
+if defined? CONFIGURE_OPTIONS
+  CONFIGURE_OPTIONS.keys.collect do |param|
+    "  --#{param}=*)\n" +
+    "    #{param.gsub("-", "_")}=`echo $i | sed 's/[-a-zA-z0-9]*=//'`\n" +
+    "    ;;\n"
+  end
+end
 }
 #{
-  if defined? CONFIGURE_H and defined? CONFIGURE_HEADERS
-    all_headers = CONFIGURE_HEADERS.collect do |header_fn|
-      "echo \"#include \\\"#{header_fn}\\\"\" > configure.check.c\n" +
-      "echo ${test_c_file} >> configure.check.c\n" +
-      "gcc configure.check.c -o configure.check.out 2>&1 | grep \"#{header_fn}: No such file\" >> /dev/null\n" +
-      "if [ \"$?\" -ne \"0\" ] ; then\n" +
-      "  echo \"#{header_fn}: yes\"\n" +
-      "  echo \"\" >> #{CONFIGURE_H}\n" +
-      "  echo \"#define HAVE_#{header_fn.upcase.gsub(".", "_")}\" >> #{CONFIGURE_H}\n" +
-      "  echo \"\" >> #{CONFIGURE_H}\n" +
-      "else\n" +
-      "  echo \"#{header_fn}: no\"\n" +
-      "fi\n" +
-      "rm -rf configure.check.c configure.check.out\n" 
-    end
-    all_headers.join "\n"
+if defined? CONFIGURE_H and defined? CONFIGURE_SWITCHES
+  CONFIGURE_SWITCHES.collect do |param, value|
+    param_var_name = "ENABLE_#{param.gsub("-", "_").upcase}"
+    "  --enable-#{param}*)\n" +
+    "    #{param_var_name}=\"true\"\n" +
+    "    ;;\n" +
+    "  --disable-#{param}*)\n" +
+    "    #{param_var_name}=\"false\"\n" +
+    "    ;;\n"
   end
+end
+}
+  *)
+    # unknown options
+    ;;
+  esac
+done
+
+
+#{
+if defined? CONFIGURE_BINARIES
+  "echo \"Checking binaries\""
+end
 }
 #{
-  if defined? CONFIGURE_H and defined? CONFIGURE_HEADERS
-    "echo \"#endif // CONFIGURE_H\" >> #{CONFIGURE_H}"
+if defined? CONFIGURE_BINARIES
+  all_binaries = CONFIGURE_BINARIES.collect do |bin_file|
+    "which #{bin_file} 2>&1 >> /dev/null\n" +
+    "if [ \"$?\" -ne \"0\" ] ; then\n" +
+    "  echo \"Binary not found: #{bin_file}\"\n" +
+    "  exit 1\n" +
+    "fi"
   end
+  all_binaries.join "\n"
+end
+}
+
+random_token=`cat /dev/urandom | od -N2 -An -i | awk '{print $1}'`
+test_filename="configure.test.`date '+%y%m%d%H%M%S'`-${random_token}"
+test_file_content="int main(){return 0;}"
+
+#{
+if defined? CONFIGURE_LIBS
+  "echo \"Checking libraries\""
+end
+}
+#{
+if defined? CONFIGURE_LIBS
+  all_libs = CONFIGURE_LIBS.collect do |lib_fn, err_msg|
+    "echo ${test_file_content} > /tmp/${test_filename}.c\n" +
+    "gcc /tmp/${test_filename}.c -l#{lib_fn[3..-1]} -o /tmp/${test_filename}.out\n" +
+    "if [ \"$?\" -ne \"0\" ] ; then\n" +
+    "  echo \"#{lib_fn}: no\"\n" +
+    "  echo \"#{err_msg}\"\n" +
+    "  rm -rf /tmp/${test_filename}.c /tmp/${test_filename}.out\n" + 
+    "  exit 1\n" +
+    "else\n" +
+    "  echo \"#{lib_fn}: yes\"\n" +
+    "  rm -rf /tmp/${test_filename}.c /tmp/${test_filename}.out\n" + 
+    "fi"
+  end
+  all_libs.join "\n"
+end
+}
+#{
+if defined? CONFIGURE_H
+  "echo \"Generating #{CONFIGURE_H}\"\n" +
+  "rm -rf #{CONFIGURE_H}\n" +
+  "echo \"// Automatically generated by './configure' on `date`\" >> #{CONFIGURE_H}\n" +
+  "echo \"#ifndef CONFIGURE_H\" >> #{CONFIGURE_H}\n" +
+  "echo \"#define CONFIGURE_H\" >> #{CONFIGURE_H}"
+end
+}
+#{
+if defined? CONFIGURE_H and defined? CONFIGURE_DEFINES
+  CONFIGURE_DEFINES.collect do |item, value|
+    "  echo \"\" >> #{CONFIGURE_H}\n" +
+    "  echo \"#define #{item} #{value}\" >> #{CONFIGURE_H}\n" +
+    "  echo \"\" >> #{CONFIGURE_H}\n"
+  end
+end
+}
+#{
+if defined? CONFIGURE_H and defined? CONFIGURE_SWITCHES
+  all_params = CONFIGURE_SWITCHES.keys.collect do |param|
+    param_var_name = "ENABLE_#{param.gsub("-", "_").upcase}"
+    "echo \"\" >> #{CONFIGURE_H}\n" +
+    "if [ ${#{param_var_name}} == \"true\" ] ; then\n" +
+    "  echo \"#define #{param_var_name} 1\" >> #{CONFIGURE_H}\n" +
+    "else\n" +
+    "  echo \"#define #{param_var_name} 0\" >> #{CONFIGURE_H}\n" +
+    "fi\n" +
+    "echo \"\" >> #{CONFIGURE_H}\n"
+  end
+  all_params.join "\n"
+end
+}
+#{
+if defined? CONFIGURE_H and defined? CONFIGURE_HEADERS
+  all_headers = CONFIGURE_HEADERS.collect do |header_fn|
+    "echo \"#include \\\"#{header_fn}\\\"\" > /tmp/${test_filename}.c\n" +
+    "echo ${test_file_content} >> /tmp/${test_filename}.c\n" +
+    "gcc /tmp/${test_filename}.c -o /tmp/${test_filename}.out 2>&1 | grep \"#{header_fn}.*No such file\" >> /dev/null\n" +
+    "if [ \"$?\" -ne \"0\" ] ; then\n" +
+    "  echo \"#{header_fn}: yes\"\n" +
+    "  echo \"\" >> #{CONFIGURE_H}\n" +
+    "  echo \"#define HAVE_#{header_fn.upcase.gsub(/\/|\./, "_")}\" >> #{CONFIGURE_H}\n" +
+    "  echo \"\" >> #{CONFIGURE_H}\n" +
+    "else\n" +
+    "  echo \"#{header_fn}: no\"\n" +
+    "fi\n" +
+    "rm -rf /tmp/${test_filename}.c /tmp/${test_filename}.out\n" 
+  end
+  all_headers.join "\n"
+end
+}
+#{
+if defined? CONFIGURE_H
+  "echo \"#endif // CONFIGURE_H\" >> #{CONFIGURE_H}"
+end
 }
 
 
@@ -846,23 +1015,14 @@ echo "# Automatically generated at `date`" >> Makefile
 echo "" >> Makefile
 echo "include Makefile.in" >> Makefile
 echo "" >> Makefile
-#{
-  if defined? DEFAULT_CONFIGURE_OPTIONS
-    all_params = DEFAULT_CONFIGURE_OPTIONS.collect do |param, value|
-      "#{param}=#{value}"
-    end
-    all_params.join "\n"
-  end
-}
-echo "" >> Makefile
 echo "install: #{INSTALL_DEPENDS.join " " if defined? INSTALL_DEPENDS}" >> Makefile 
 #{
-  if defined? INSTALL_ACTIONS
-    all_actions = INSTALL_ACTIONS.collect do |action|
-      "echo \"\t#{action}\" >> Makefile"
-    end
-    all_actions.join "\n"
+if defined? INSTALL_ACTIONS
+  all_actions = INSTALL_ACTIONS.collect do |action|
+    "echo \"\t#{action}\" >> Makefile"
   end
+  all_actions.join "\n"
+end
 }
 
 CFG_FILE
