1.add the func of brief command 2.now if the command is wrong (lack of para), will report instead running wrong in java app

diff --git a/client/shell/bin/novashell b/client/shell/bin/novashell
--- a/client/shell/bin/novashell
+++ b/client/shell/bin/novashell
@@ -8,12 +8,42 @@ if [ ! $NOVASHELL_CONF_DIR ]; then
 	NOVASHELL_CONF_DIR=$PWD/../conf/
 fi
 
-if [ "$1" == "list-clusters" ]; then
+if [ "$1" == "list-clusters" ] ||
+   [ "$1" == "lcs" ]; then
   java -Xbootclasspath/a:../lib/jdom.jar:../lib/httpclient-4.0.2.jar:../lib/commons-logging-1.1.1.jar:../lib/gson-1.5.jar:../lib/httpcore-4.0.1.jar:../lib/httpcore-nio-4.0.1.jar:../lib/httpmime-4.0.2.jar -jar ../nova-client.jar $NOVASHELL_CONF_DIR $1
   exit 0
-elif [ "$1" == "start-vmachines" ] ||
-       	[ "$1" == "destroy-vmachines" ] || [ "$1" == "suspend-vmachines" ] || [ "$1" == "resume-vmachines" ] || [ "$1" == "create-cluster" ] || [ "$1" == "list-vmachines" ] || [ "$1" == "list-vmachineinfo" ]; then
-  java -Xbootclasspath/a:../lib/jdom.jar:../lib/httpclient-4.0.2.jar:../lib/commons-logging-1.1.1.jar:../lib/gson-1.5.jar:../lib/httpcore-4.0.1.jar:../lib/httpcore-nio-4.0.1.jar:../lib/httpmime-4.0.2.jar -jar ../nova-client.jar $NOVASHELL_CONF_DIR $1 $2 $3
+elif
+   [ "$1" == "start-vmachines" ] ||
+   [ "$1" == "sv" ] ||
+   [ "$1" == "destroy-vmachines" ] ||
+   [ "$1" == "dv" ] ||
+   [ "$1" == "suspend-vmachines" ] ||
+   [ "$1" == "ssv" ] ||
+   [ "$1" == "resume-vmachines" ] ||
+   [ "$1" == "rv" ] ||
+   [ "$1" == "create-cluster" ] ||
+   [ "$1" == "cc" ] ||
+   [ "$1" == "list-vmachines" ] ||
+   [ "$1" == "lvs" ] ||
+   [ "$1" == "list-vmachineinfo" ] ||
+   [ "$1" == "lvi" ]; then
+
+   if [ "$2" == "" ]; then
+	   if [ "$1" == "list-vmachines" ] ||
+              [ "$1" == "lvs" ]; then
+	   	echo "error: need vclustername"
+	   	exit 1
+	   elif 
+	      [ "$1" == "create-cluster" ] ||
+              [ "$1" == "cc" ]; then
+	   	echo "error: need filePath"
+	   	exit 1
+	   else
+	   	echo "error: need machineuuid"
+	   	exit 1
+   	   fi
+   fi
+   java -Xbootclasspath/a:../lib/jdom.jar:../lib/httpclient-4.0.2.jar:../lib/commons-logging-1.1.1.jar:../lib/gson-1.5.jar:../lib/httpcore-4.0.1.jar:../lib/httpcore-nio-4.0.1.jar:../lib/httpmime-4.0.2.jar -jar ../nova-client.jar $NOVASHELL_CONF_DIR $1 $2 $3
   exit 0
 fi
 
@@ -21,14 +51,14 @@ fi
 if [ "$1" ] || [ "$#" == 0 ]; then
 	echo "Usage: nova COMMAND"
 	echo "where COMMAND is one of:"
-	echo "  list-clusters"
-	echo "  list-vmachines    vclustername"
-	echo "  list-vmachineinfo machineuuid"
-	echo "  start-vmachines   vmachinename(uuid) [sched_to]"
-	echo "  destroy-vmachines vmachinename"
-	echo "  suspend-vmachines vmachinename"
-	echo "  resume-vmachines  vmachinename"
-	echo "  create-cluster    filePath"
+	echo "  list-clusters(lcs)"
+	echo "  list-vmachines(lvs)    vclustername"
+	echo "  list-vmachineinfo(lvi) machineuuid"
+	echo "  start-vmachines(sv)    machineuuid [sched_to]"
+	echo "  destroy-vmachines(dv)  machineuuid"
+	echo "  suspend-vmachines(ssv) machineuuid"
+	echo "  resume-vmachines(rv)   machineuuid"
+	echo "  create-cluster(cc)     filePath"
 	exit 1
 fi
 
